name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: x86_64-apple-darwin
            os: macos-latest
            name: mcp-bookmark-darwin-x64
          - target: aarch64-apple-darwin
            os: macos-latest
            name: mcp-bookmark-darwin-arm64

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      
      - name: Build
        run: |
          cargo build --release --target ${{ matrix.target }} --bin mcp-bookmark
          cargo build --release --target ${{ matrix.target }} --bin mcp-bookmark-native
      
      - name: Prepare binaries
        shell: bash
        run: |
          # Prepare mcp-bookmark
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            cp target/${{ matrix.target }}/release/mcp-bookmark.exe ${{ matrix.name }}
            cp target/${{ matrix.target }}/release/mcp-bookmark-native.exe ${{ matrix.name }}-native
          else
            cp target/${{ matrix.target }}/release/mcp-bookmark ${{ matrix.name }}
            cp target/${{ matrix.target }}/release/mcp-bookmark-native ${{ matrix.name }}-native
            chmod +x ${{ matrix.name }}
            chmod +x ${{ matrix.name }}-native
          fi
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: |
            ${{ matrix.name }}
            ${{ matrix.name }}-native

  package-extension:
    name: Package Chrome Extension
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Package Chrome Extension
        run: |
          cd bookmark-indexer-extension
          zip -r ../bookmark-indexer-chrome-extension.zip . \
            -x "*.DS_Store" \
            -x "__MACOSX/*" \
            -x ".git/*" \
            -x "*.md"
      
      - name: Upload extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension
          path: bookmark-indexer-chrome-extension.zip

  release:
    name: Create Release
    needs: [build, package-extension]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*
          draft: false
          prerelease: false
          generate_release_notes: true
          body: |
            ## Installation
            
            ### Quick Setup (Recommended)
            Clone the repository and run the installation script:
            ```bash
            git clone https://github.com/${{ github.repository }}.git
            cd mcp-bookmark
            ./install.sh
            ```
            
            ### Manual Binary Download
            
            #### macOS (Intel)
            ```bash
            # Download both binaries
            curl -L https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/mcp-bookmark-darwin-x64 -o mcp-bookmark
            curl -L https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/mcp-bookmark-darwin-x64-native -o mcp-bookmark-native
            chmod +x mcp-bookmark mcp-bookmark-native
            ```
            
            #### macOS (Apple Silicon)
            ```bash
            # Download both binaries
            curl -L https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/mcp-bookmark-darwin-arm64 -o mcp-bookmark
            curl -L https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/mcp-bookmark-darwin-arm64-native -o mcp-bookmark-native
            chmod +x mcp-bookmark mcp-bookmark-native
            ```
            
            ## Quick Start
            
            ### 1. Install Chrome Extension
            
            Download the Chrome extension package from this release:
            - **[bookmark-indexer-chrome-extension.zip](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/bookmark-indexer-chrome-extension.zip)**
            
            Installation steps:
            1. Download and extract the ZIP file
            2. Open Chrome and navigate to `chrome://extensions/`
            3. Enable "Developer mode"
            4. Click "Load unpacked" and select the extracted folder
            5. Configure Native Messaging Host with `mcp-bookmark-native` binary
            
            See [Extension README](https://github.com/${{ github.repository }}/tree/main/bookmark-indexer-extension) for detailed setup
            
            ### 2. Configure and Run MCP Server
            
            ```bash
            # List available indexes
            ./mcp-bookmark --list-indexes
            
            # Run with specific index
            INDEX_NAME="YourIndexName" ./mcp-bookmark
            
            # Or create .mcp.json configuration file
            ```
            
            **Features**: 
            - 🔐 Works with authenticated pages
            - ⚡ Fast local search with Tantivy
            - 🎯 AI-friendly for Claude
            
            **Requirements**: macOS + Google Chrome
            
            See [full documentation](https://github.com/${{ github.repository }}) for configuration details.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}